plugins:
  - jekyll-paginate

title: arzamaskov
description:
  Блог о веб-разработке

timezone: Europe/Ulyanovsk

excerpt_separator: <!--more-->

paginate: 10
paginate_path: /page/:num/
permalink: /:title/
