# Site settings
url: "https://arzamaskov.github.io/"
baseurl: "" # the subpath of your site, e.g. /blog
title: "arzamaskov"
description: "personal blog"
email: "arzamaskov@gmail.com"
author: "Andrey Arzamaskov"
date_format: "%d.%m.%Y"
lang: ru
intro: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
sass:
  style: compressed
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
